version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 73CMdunRhczkB3ih
      MYSQL_DATABASE: mydb