name: Actualizar Servidor de Producci贸n

on:
  push:
    branches:
      - dev 

jobs:
  actualizar-servidor:
    runs-on: ubuntu-latest 

    steps:
      - name: Chequear c贸digo en el servidor
        uses: actions/checkout@v4

      - name: Add github.com to known hosts
        run: ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Dar permisos de ejecuci贸n al script
        run: chmod +x update.sh

      - name: Node version
        run: node -v

      - name: Instalar pm2
        run: npm install pm2 -g

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Actualizar servidor de producci贸n
        run: ./update.sh
