name: Actualizar Servidor de Producci贸n

on:
  push:
    branches:
      - dev 

jobs:
  actualizar-servidor:
    runs-on: ubuntu-latest 

    steps:
      - name: Chequear c贸digo en el servidor
        uses: actions/checkout@v2

      - name: Dar permisos de ejecuci贸n al script
        run: chmod +x update.sh

      - name: Actualizar servidor de producci贸n
        run: ./update.sh
